server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"

spring:
  datasource:
    url:  jdbc:h2:~/test;MODE=MySQL
    driverClassName: org.h2.Driver
    username: codeit
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
#      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: 'true'


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json



